--
-- PostgreSQL database dump
--

\restrict Vpua5iUEtKkpGyHRfkiv22txloNZsW9bdhHfdiRVKw51haWLaMbXJrDhpYDN1vK

-- Dumped from database version 17.10
-- Dumped by pg_dump version 17.10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: about; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.about (
    id bigint NOT NULL,
    available_for_freelance boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    role character varying(150) NOT NULL,
    description text NOT NULL,
    headline character varying(150) NOT NULL,
    location character varying(150) NOT NULL,
    specialization character varying(150) NOT NULL,
    summary character varying(500) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);


--
-- Name: about_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.about ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.about_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contact_messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contact_messages (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    email character varying(254) NOT NULL,
    message character varying(5000) NOT NULL,
    name character varying(100) NOT NULL,
    subject character varying(150) NOT NULL
);


--
-- Name: contact_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.contact_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contact_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: experiences; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.experiences (
    id bigint NOT NULL,
    company character varying(150) NOT NULL,
    current boolean NOT NULL,
    description character varying(5000) NOT NULL,
    display_order integer NOT NULL,
    employment_type character varying(100) NOT NULL,
    end_date date,
    location character varying(150) NOT NULL,
    role character varying(150) NOT NULL,
    start_date date NOT NULL
);


--
-- Name: experiences_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.experiences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.experiences_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notes (
    id bigint NOT NULL,
    category character varying(100) NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    display_order integer NOT NULL,
    published boolean NOT NULL,
    slug character varying(100) NOT NULL,
    summary character varying(500) NOT NULL,
    title character varying(200) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);


--
-- Name: notes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: projects; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.projects (
    id bigint NOT NULL,
    description character varying(2000) NOT NULL,
    featured boolean NOT NULL,
    github_url character varying(500),
    image_url character varying(500),
    live_url character varying(500),
    technologies character varying(1000) NOT NULL,
    title character varying(150) NOT NULL
);


--
-- Name: projects_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.projects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projects_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: resumes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.resumes (
    id bigint NOT NULL,
    active boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    file_url character varying(500) NOT NULL,
    title character varying(150) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    version character varying(50) NOT NULL
);


--
-- Name: resumes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.resumes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resumes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: services; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.services (
    id bigint NOT NULL,
    active boolean NOT NULL,
    category character varying(100) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    description text NOT NULL,
    display_order integer NOT NULL,
    icon character varying(100),
    slug character varying(150) NOT NULL,
    technologies text NOT NULL,
    title character varying(150) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);


--
-- Name: services_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.services ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.services_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: skills; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.skills (
    id bigint NOT NULL,
    category character varying(100) NOT NULL,
    display_order integer NOT NULL,
    name character varying(100) NOT NULL,
    proficiency integer NOT NULL
);


--
-- Name: skills_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.skills ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.skills_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: about about_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.about
    ADD CONSTRAINT about_pkey PRIMARY KEY (id);


--
-- Name: contact_messages contact_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contact_messages
    ADD CONSTRAINT contact_messages_pkey PRIMARY KEY (id);


--
-- Name: experiences experiences_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.experiences
    ADD CONSTRAINT experiences_pkey PRIMARY KEY (id);


--
-- Name: notes notes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notes
    ADD CONSTRAINT notes_pkey PRIMARY KEY (id);


--
-- Name: projects projects_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT projects_pkey PRIMARY KEY (id);


--
-- Name: resumes resumes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resumes
    ADD CONSTRAINT resumes_pkey PRIMARY KEY (id);


--
-- Name: services services_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.services
    ADD CONSTRAINT services_pkey PRIMARY KEY (id);


--
-- Name: skills skills_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.skills
    ADD CONSTRAINT skills_pkey PRIMARY KEY (id);


--
-- Name: services ukgnenm2itqjotnod9yfan1e9in; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.services
    ADD CONSTRAINT ukgnenm2itqjotnod9yfan1e9in UNIQUE (slug);


--
-- Name: idx_projects_featured; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_projects_featured ON public.projects USING btree (featured);


--
-- Name: idx_projects_title; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_projects_title ON public.projects USING btree (title);


--
-- PostgreSQL database dump complete
--

\unrestrict Vpua5iUEtKkpGyHRfkiv22txloNZsW9bdhHfdiRVKw51haWLaMbXJrDhpYDN1vK

